version: '3'
services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1096m" # 設置使用jvm內存大小
      - "ES_HEAP_SIZE=512m"
      - "MAX_OPEN_FILES=65535"
      - "MAX_LOCKED_MEMORY=unlimited"
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./es/data:/usr/share/elasticsearch/data:rw # 數據文件掛載
      - ./es/logs:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch # kibana在elasticsearch啟動之後再啟動
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200 # 設置訪問elasticsearch的地址
      I18N_LOCALE: zh-CN
    ports:
      - 5601:5601
  logstash:
    build:
      context: .
      dockerfile: Dockerfile.logstash
      args:
        STACK_VERSION: ${STACK_VERSION}
    image: logstash
    container_name: logstash
    depends_on:
      - elasticsearch # logstash在elasticsearch啟動之後再啟動
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro # 將 Logstash pipeline 配置文件掛載到容器中
      - ./jdbc_drivers/mysql-connector-java-8.0.23.jar:/usr/share/logstash/jdbc_drivers/mysql-connector-java-8.0.23.jar:ro # 將 JDBC 驅動文件掛載到容器中
      - ./backup/csv:/usr/mysql_backup/csv
    ports:
      - 5044:5044 # 預設 Logstash 的 Beats input port
    environment:
      - "XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200" # 設置監控地址
    command: logstash -f /usr/share/logstash/pipeline/pip install elasticsearch${LOGSTASH_CONF_PATH} # 設置 Logstash 配置文件